using System.Collections.Generic;
using System.Text;

namespace Narazaka.Unity.LilToonShaderMerger
{
    public static class HlslEmitter
    {
        public static string EmitCustomHlsl(MergedHlsl merged)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by lilToon Shader Merger");
            sb.AppendLine();

            // 複数行マクロ
            foreach (var kv in merged.MultilineMacros)
            {
                sb.AppendLine($"#define {kv.Key} \\");
                for (int i = 0; i < kv.Value.Count; i++)
                {
                    bool isLast = i == kv.Value.Count - 1;
                    sb.AppendLine(isLast ? $"    {kv.Value[i]}" : $"    {kv.Value[i]}\\");
                }
                sb.AppendLine();
            }

            // フラグマクロ
            foreach (var f in merged.FlagMacros) sb.AppendLine($"#define {f}");
            return sb.ToString();
        }

        public static string EmitCustomInsertHlsl(IReadOnlyList<(string sourceKey, string body)> sources)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by lilToon Shader Merger");
            sb.AppendLine();
            foreach (var (key, body) in sources)
            {
                sb.AppendLine($"// --- {key} ---");
                sb.AppendLine(body);
                sb.AppendLine();
            }
            return sb.ToString();
        }
    }
}
