using System.Collections.Generic;
using System.Text;

namespace Narazaka.Unity.LilToonShaderMerger
{
    public static class HlslEmitter
    {
        public static string EmitCustomHlsl(MergedHlsl merged)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by lilToon Shader Merger");
            sb.AppendLine();

            // 条件が同じ要素が続く間は 1 つの #if ... #endif にまとめる
            HlslEntry open = null;
            foreach (var e in merged.Entries)
            {
                if (open != null && !open.SameConditions(e))
                {
                    CloseConditions(sb, open);
                    open = null;
                }
                if (open == null)
                {
                    foreach (var frame in e.Conditions)
                        foreach (var header in frame) sb.AppendLine(header);
                    open = e;
                }
                AppendEntry(sb, e);
            }
            if (open != null) CloseConditions(sb, open);
            return sb.ToString();
        }

        static void CloseConditions(StringBuilder sb, HlslEntry e)
        {
            for (int i = 0; i < e.Conditions.Count; i++) sb.AppendLine("#endif");
        }

        static void AppendEntry(StringBuilder sb, HlslEntry e)
        {
            switch (e.Kind)
            {
                case HlslEntryKind.Undef:
                    sb.AppendLine($"#undef {e.Name}");
                    break;
                case HlslEntryKind.Other:
                    foreach (var ln in e.Body) sb.AppendLine(ln);
                    break;
                default:
                    var head = $"#define {e.Name}{e.Params}";
                    if (e.Body.Count == 0) sb.AppendLine(head);
                    else if (e.Body.Count == 1) sb.AppendLine($"{head} {e.Body[0]}");
                    else
                    {
                        sb.AppendLine($"{head} \\");
                        for (int i = 0; i < e.Body.Count; i++)
                            sb.AppendLine(i == e.Body.Count - 1 ? $"    {e.Body[i]}" : $"    {e.Body[i]}\\");
                    }
                    break;
            }
        }

        public static string EmitCustomInsertHlsl(IReadOnlyList<(string sourceKey, string body)> sources)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Auto-generated by lilToon Shader Merger");
            sb.AppendLine();
            foreach (var (key, body) in sources)
            {
                sb.AppendLine($"// --- {key} ---");
                sb.AppendLine(body);
                sb.AppendLine();
            }
            return sb.ToString();
        }
    }
}
